server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://139.199.89.142:3306/bx_travels?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: bx123@@
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1

  #thymeleaf 模板引擎 Start
  thymeleaf:
    # spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存，不然无法看到页面实时刷新（生产环境则设置为true）
    cache: false
    #扫描页面路径
    prefix: classpath:/templates/
    #页面的后缀名
    suffix: .html


  #thymeleaf 模板引擎 End
mybatis:
  mapper-locations: classpath:mappers/*.xml
#xml文件路径
  #实体类路径
  type-aliases-package: com.bxkj.commodity.entity